#theme: jekyll-theme-hacker
theme: jekyll-sleek
title: Sganachari
description: Write-ups on the things I have worked
google_analytics: G-E06KRZ9HZ7
show_github_page: False
github:
  zip_url: http://example.com/download.zip
  another_url: https://sganachari.xyz/download.zip
